version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: techtrend_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: techtrend

  backend:
    build:
      context: ./backend
    container_name: techtrend_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongodb:27017/techtrend
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: techtrend_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8000
    depends_on:
      - backend

volumes:
  mongo_data:
